import { NextApiRequest, NextApiResponse } from 'next';

import { createAdminClient } from '@/lib/supabase';
import getUserId from '@/lib/handleSession';

// Define the expected structure of a row from the uploaded file
interface UploadedResident {
  first_name?: string;
  last_name?: string;
  resident_id?: string; // This corresponds to student_id in the database
  email?: string;
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<{ message: string } | { error: string }>
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { residents: newResidentsData, orgSlug, mailroomSlug } = req.body as { residents: UploadedResident[], orgSlug: string, mailroomSlug: string };

  if (!newResidentsData || !Array.isArray(newResidentsData) || newResidentsData.length === 0 || !orgSlug || !mailroomSlug) {
    return res.status(400).json({ error: 'No resident data provided, or orgSlug/mailroomSlug missing, or data is invalid.' });
  }

  try {
    const supabaseAdmin = createAdminClient();
    const authHeader = req.headers.authorization;
    const userId = await getUserId(supabaseAdmin, authHeader);

    if (!userId) {
      return res.status(401).json({ error: 'User not authenticated or staff ID cannot be determined for logging.' });
    }

    // Fetch mailroom_id based on orgSlug and mailroomSlug
    const { data: mailroomRecord, error: mailroomFetchError } = await supabaseAdmin
      .from('mailrooms')
      .select('id, organization_id')
      .eq('slug', mailroomSlug)
      .single();

    if (mailroomFetchError || !mailroomRecord) {
      console.error(`Error fetching mailroom by slug ${mailroomSlug}:`, mailroomFetchError);
      return res.status(404).json({ error: 'Mailroom not found.' });
    }

    const { data: orgData, error: orgFetchError } = await supabaseAdmin
      .from('organizations')
      .select('id')
      .eq('slug', orgSlug)
      .eq('id', mailroomRecord.organization_id)
      .single();

    if (orgFetchError || !orgData) {
      console.error(`Error fetching organization by slug ${orgSlug} or mailroom mismatch:`, orgFetchError);
      return res.status(404).json({ error: 'Organization not found or mailroom does not belong to it.' });
    }
    
    const mailroomId = mailroomRecord.id;

    // Validate incoming data - ensure required fields are present
    for (const resident of newResidentsData) {
      if (!resident.first_name || !resident.last_name || !resident.resident_id) {
        // Email is optional based on schema, but good to have.
        // student_id is critical.
        return res.status(400).json({ error: `Missing required fields for one or more residents. Ensure first_name, last_name, and resident_id are present. Problematic entry: ${JSON.stringify(resident)}` });
      }
    }
    
    // Supabase doesn't directly support transactions in the same way as traditional SQL through the JS client for multiple table operations like this.
    // We need to perform these operations sequentially and handle potential partial failures.
    // A more robust solution might involve a database function (stored procedure) to handle this atomically.

    // 1. Update existing active residents to 'REMOVED_BULK'
    const { error: updateError } = await supabaseAdmin
      .from('residents')
      .update({ status: 'REMOVED_BULK', updated_at: new Date().toISOString() })
      .eq('mailroom_id', mailroomId)
      .eq('status', 'ACTIVE');

    if (updateError) {
      console.error('Error updating existing residents:', updateError);
      // Decide if we should proceed or return an error. 
      // For now, let's return an error to avoid inconsistent state.
      return res.status(500).json({ error: 'Failed to update existing residents.' });
    }

    // 2. Prepare and insert new residents
    const residentsToInsert = newResidentsData.map(resData => ({
      mailroom_id: mailroomId,
      first_name: resData.first_name,
      last_name: resData.last_name,
      student_id: resData.resident_id, // Map resident_id from file to student_id in DB
      email: resData.email,
      added_by: userId,
      status: 'ACTIVE', // New residents are active by default
      // created_at and id will be auto-generated by Supabase
    }));

    const { data: insertedData, error: insertError } = await supabaseAdmin
      .from('residents')
      .insert(residentsToInsert)
      .select(); // Optionally select the inserted data if needed

    if (insertError) {
      console.error('Error inserting new residents:', insertError);
      // Potentially, we might want to try and rollback the status update if this fails,
      // but that's complex without true transactions.
      // For now, this could lead to a state where old residents are marked REMOVED_BULK but new ones aren't added.
      return res.status(500).json({ error: `Failed to insert new residents: ${insertError.message}` });
    }

    const count = insertedData?.length || 0;
    return res.status(200).json({ message: `${count} residents successfully uploaded and added.` });

  } catch (error: unknown) {
    console.error('Error processing roster upload:', error);
    let errorMessage = 'Internal server error';
    if (error instanceof Error) {
      errorMessage = error.message;
    }
    return res.status(500).json({ error: errorMessage });
  }
} 